name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/Cadair/parfive/_build/results?buildId=$(Build.BuildId)"

resources:
  repositories:
  - repository: sunpy
    type: github
    endpoint: Cadair
    name: sunpy/azure-pipelines-template
    ref: master

trigger:
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_py37
    os: linux
    tox: py37 --

- template: run-tox-env.yml@sunpy
  parameters:
    name: Windows_py36
    os: windows
    tox: py36 --

# - template: run-tox-env.yml@sunpy
#   parameters:
#     name: MacOS_35
#     os: macos
#     tox: py35 --

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@sunpy
    parameters:
      dependsOn: [Linux_35,Windows_py36,MacOS_py37]
