[tool.towncrier]
    package = "parfive"
    package_dir = "."
    directory = "changelog"
    filename = "docs/CHANGELOG.rst"
    issue_format = "`#{issue} <https://github.com/Cadair/parfive/pull/{issue}>`__"
